app:
    image: quay.io/erasche/galactic-radio-telescope:latest
    ports:
      - 8000:8000
    links:
      - db
    environment:
      DJANGO_DEBUG: 'False'
      DJANGO_ALLOWED_HOSTS: '*'
      DJANGO_URL_PREFIX: 'grt-admin/'

db:
    image: postgres:9.5
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

dbbackup:
    image: quay.io/tamu_cpt/postgres-backup:latest
    environment:
      MAX_BACKUPS: 5
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
    links:
      - db
    volumes:
      - ./pg_backup:/backup
